### ISSUE TITLE
CH always redirects to tab 0

### ISSUE THREAD

**Issue by noxhirsch** [maykar/custom-header#27]
The new Custom Header redirects always to tab 0 even if no default is set. In the editor I can see a 0 in default_tab but can't remove it (it always reappears).
This is my config:
```
custom_header:
  chevrons: false
  compact_mode: true
  editor_warnings: false
  hide_help: true
  menu_hide: true
  voice_hide: true
  hidden_tab_redirect: false
  hide_tabs: 'floorplan, feed'
```

Thank you for help!

EDIT:
- I'm using HA 103.0, CA 1.0.1 & up2date Chrome on Win10
- No relevant errors in Console & Log

**Comment by maykar** [comment]
Fix will be in the next release, thank you.

**Comment by maykar** [comment]
Should be fixed in latest release

**Comment by iptvcld** [comment]
this did not fix the issue - when refreshing the page, still jumps to tab 0
custom_header:
  compact_mode: true
  hide_help: true
  voice_hide: true
  options_hide: true
  sidebar_closed: true
  background: transparent url("/local/backgrounds/53.png")
  active_tab_color: black
  tab_indicator_color: red
  all_tabs_color: "#6B6C6C"
  button_color:
    options: black
  exceptions:
    - conditions:
        user_agent: Mobile
      config:
        tab_indicator_color: red
        background:
        active_tab_color: black
        all_tabs_color:
        disable_sidebar: false
        menu_hide: true

**Comment by iptvcld** [comment]
Dont think its an issue with your addon - i tried to disable the custom header and still happening

**Comment by noxhirsch** [comment]
> Dont think its an issue with your addon - i tried to disable the custom header and still happening

I actually was an issue with the addon (for me) and it's indeed fixed now. Did you disable the custom header with `?disable_ch` in the URL? For me the issue was gone with that.

**Comment by iptvcld** [comment]
with 1.0.6 - the issue has been fixed for me. Thanks
